# Generated by Django 3.0 on 2020-06-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases_information', '0027_delete_crimeimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeSceneImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=300)),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases_information.CrimeDetail')),
            ],
        ),
    ]
