# Generated by Django 3.0 on 2020-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
