# Generated by Django 3.0 on 2020-05-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0002_auto_20200418_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuseraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=200, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='publicuseraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=200, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='publicuseraddress',
            name='zip_code',
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
