# Generated by Django 3.0 on 2020-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0003_auto_20200510_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuseraddress',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
