# Generated by Django 3.0 on 2020-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0006_publicuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='publicuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='publicuser_profile_images'),
        ),
    ]
