# Generated by Django 3.0 on 2020-06-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0007_auto_20200603_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicuser',
            old_name='profile_image',
            new_name='public_user_profile_image',
        ),
    ]
