# Generated by Django 3.0 on 2020-06-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0008_auto_20200603_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicuser',
            old_name='public_user_profile_image',
            new_name='profile_image',
        ),
    ]
