# Generated by Django 3.0 on 2020-06-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0011_auto_20200603_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='publicuser_profile_images')),
            ],
        ),
    ]
