# Generated by Django 3.0 on 2020-06-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0012_imagedemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
