# Generated by Django 3.0 on 2020-05-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=200, default=0, max_digits='300'),
        ),
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=200, default=0, max_digits='300'),
        ),
    ]
