# Generated by Django 3.0 on 2020-05-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0003_auto_20200510_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=200, default=0, max_digits=300),
        ),
    ]
