# Generated by Django 3.0 on 2020-05-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_users_app', '0004_auto_20200510_0050'),
        ('crime_reporting_app', '0004_auto_20200510_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereported',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public_users_app.PublicUser'),
            preserve_default=False,
        ),
    ]
