# Generated by Django 3.0 on 2020-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0005_crimereported_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=300),
        ),
    ]
