# Generated by Django 3.0 on 2020-05-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0006_auto_20200511_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimereportedlocation',
            old_name='crime_reported',
            new_name='resident_id',
        ),
    ]
