# Generated by Django 3.0 on 2020-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0007_auto_20200519_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='crimereportedlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=300),
        ),
    ]
