# Generated by Django 3.0 on 2020-06-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0008_auto_20200520_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereported',
            name='final_submit',
            field=models.BooleanField(default=False),
        ),
    ]
