# Generated by Django 3.0 on 2020-06-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_reporting_app', '0009_crimereported_final_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereported',
            name='remarks',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
