# Generated by Django 3.0 on 2020-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0002_auto_20200403_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetail',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='criminaldetail',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimdetail',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetail',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='victimdetail',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victimdetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
