# Generated by Django 3.0 on 2020-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0003_auto_20200403_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetail',
            name='aadhar_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimdetail',
            name='aadhar_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
