# Generated by Django 3.0 on 2020-04-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0004_auto_20200403_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalDetailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.PositiveIntegerField()),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VictimDetailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.PositiveIntegerField()),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='criminaldetail',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='victimdetail',
            name='address_id',
        ),
        migrations.DeleteModel(
            name='CriminalVictimAddress',
        ),
        migrations.AddField(
            model_name='victimdetailaddress',
            name='victim_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='criminal_and_victim_details.VictimDetail'),
        ),
        migrations.AddField(
            model_name='criminaldetailaddress',
            name='criminal_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='criminal_and_victim_details.CriminalDetail'),
        ),
    ]
