# Generated by Django 3.0 on 2020-04-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0006_auto_20200403_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminaldetail',
            old_name='aadhar_no',
            new_name='adhaar_no',
        ),
        migrations.RenameField(
            model_name='victimdetail',
            old_name='aadhar_no',
            new_name='adhaar_no',
        ),
    ]
