# Generated by Django 3.0 on 2020-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0007_auto_20200403_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetail',
            name='occupation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='criminaldetail',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='victimdetail',
            name='occupation',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victimdetail',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
