# Generated by Django 3.0 on 2020-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0009_victimdetail_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetail',
            name='remarks',
            field=models.CharField(blank=True, default='unknown', max_length=500, null=True),
        ),
    ]
