# Generated by Django 3.0 on 2020-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0011_auto_20200510_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetailaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='criminaldetailaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='victimdetailaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=300),
        ),
        migrations.AlterField(
            model_name='victimdetailaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=300),
        ),
    ]
