# Generated by Django 3.0 on 2020-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_and_victim_details', '0012_auto_20200524_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminaldetail',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='victimdetail',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
