# Generated by Django 3.0 on 2020-06-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_contact_us_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymodel',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='querymodel',
            name='dou',
        ),
    ]
