# Generated by Django 3.0 on 2020-06-09 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_contact_us_app', '0002_auto_20200608_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='doc',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 9, 7, 1, 15, 524697, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querymodel',
            name='dou',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
