# Generated by Django 3.0 on 2020-06-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_user_contact_us_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymodel',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='querymodel',
            name='dou',
        ),
    ]
