# Generated by Django 3.0 on 2020-06-09 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public_user_contact_us_app', '0002_auto_20200609_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='doc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querymodel',
            name='dou',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
