# Generated by Django 3.0 on 2020-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigatorprofile',
            name='adhaar_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='doc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='dou',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investigatorprofile',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatorprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investigatorprofile',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigatorprofile',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
