# Generated by Django 3.0 on 2020-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0002_auto_20200321_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatorprofile',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
