# Generated by Django 3.0 on 2020-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0003_auto_20200321_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatorprofile',
            name='password',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
