# Generated by Django 3.0 on 2020-03-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0005_investigatoraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestigatorAddress',
            new_name='InvestigatorAddres',
        ),
    ]
