# Generated by Django 3.0 on 2020-03-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0006_auto_20200321_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestigatorAddres',
            new_name='InvestigatorAddress',
        ),
    ]
