# Generated by Django 3.0 on 2020-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0008_auto_20200330_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_otp', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
