# Generated by Django 3.0 on 2020-03-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0009_passwordrest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRest',
        ),
        migrations.RenameField(
            model_name='investigatorprofile',
            old_name='email_verification_token',
            new_name='email_token',
        ),
    ]
