# Generated by Django 3.0 on 2020-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0010_auto_20200331_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='investigatorprofile',
            old_name='email_token',
            new_name='email_verification_token',
        ),
    ]
