# Generated by Django 3.0 on 2020-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0011_auto_20200401_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrest',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
