# Generated by Django 3.0 on 2020-04-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0012_auto_20200402_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRest',
        ),
    ]
