# Generated by Django 3.0 on 2020-04-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0013_delete_passwordrest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigatoraddress',
            old_name='Investigator_id',
            new_name='resident_id',
        ),
    ]
