# Generated by Django 3.0 on 2020-04-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0014_auto_20200411_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigatorprofile',
            name='position',
        ),
        migrations.CreateModel(
            name='InvestigatorsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('achivements', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=200)),
                ('email', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
