# Generated by Django 3.0 on 2020-04-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0015_auto_20200413_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestigatorsDetail',
            new_name='InvestigatorsAdministrativeDetail',
        ),
    ]
