# Generated by Django 3.0 on 2020-04-13 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0017_auto_20200414_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigatorsadministrativedetail',
            name='email',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
