# Generated by Django 3.0 on 2020-06-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_manage', '0019_auto_20200524_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigatorprofile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
