# Generated by Django 3.0 on 2020-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0002_auto_20200330_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetail',
            name='investigator_id',
            field=models.EmailField(max_length=200),
        ),
    ]
