# Generated by Django 3.0 on 2020-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0004_auto_20200403_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetail',
            name='investigator_id',
            field=models.EmailField(max_length=200),
        ),
    ]
