# Generated by Django 3.0 on 2020-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0005_auto_20200403_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedetail',
            name='type_of_crimes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
