# Generated by Django 3.0 on 2020-04-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0006_crimedetail_type_of_crimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimedetail',
            old_name='type_of_crimes',
            new_name='type_of_crime',
        ),
        migrations.CreateModel(
            name='CrimeLiveUpdation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('doc', models.DateTimeField(auto_now_add=True)),
                ('crime_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cases_information.CrimeDetail')),
            ],
        ),
    ]
