# Generated by Django 3.0 on 2020-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0007_auto_20200406_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetail',
            name='type_of_crime',
            field=models.CharField(blank=True, choices=[('Robbery', 'Robbery'), ('Murder', 'Murder'), ('Acid Throwing', 'Acid Throwing'), ('Ragging', 'Ragging'), ('Property', 'Property '), ('Others', 'Others'), ('Smuggling', 'Smuggling'), ('Vandalism', 'Vandalism'), ('Torture', 'Torture')], max_length=300, null=True),
        ),
    ]
