# Generated by Django 3.0 on 2020-04-09 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0008_auto_20200406_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimedetail',
            name='occurance_time',
        ),
        migrations.AddField(
            model_name='crimedetail',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='crimedetail',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
