# Generated by Django 3.0 on 2020-04-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0009_auto_20200409_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
