# Generated by Django 3.0 on 2020-05-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0011_auto_20200510_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimelocationdetail',
            old_name='crime_id',
            new_name='resident_id',
        ),
        migrations.RemoveField(
            model_name='crimelocationdetail',
            name='address',
        ),
        migrations.AddField(
            model_name='crimelocationdetail',
            name='city',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='crimelocationdetail',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=300),
        ),
        migrations.AddField(
            model_name='crimelocationdetail',
            name='location',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='crimelocationdetail',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=300),
        ),
        migrations.AddField(
            model_name='crimelocationdetail',
            name='state',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='crimelocationdetail',
            name='zip_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
