# Generated by Django 3.0 on 2020-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0014_auto_20200524_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetail',
            name='investigator_id',
            field=models.EmailField(max_length=200),
        ),
    ]
