# Generated by Django 3.0 on 2020-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0016_auto_20200524_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedetail',
            name='investigator',
            field=models.EmailField(max_length=300),
        ),
    ]
