# Generated by Django 3.0 on 2020-05-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0017_auto_20200524_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimedetail',
            old_name='investigator',
            new_name='investigator_id',
        ),
    ]
