# Generated by Django 3.0 on 2020-06-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0024_auto_20200524_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimeliveupdation',
            name='dou',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
