# Generated by Django 3.0 on 2020-06-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases_information', '0026_crimeimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrimeImages',
        ),
    ]
